#!/bin/bash

sed -i -e '/CONFIG_MAKE_TOOLCHAIN=y/d' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_IB=y/# CONFIG_IB is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_SDK=y/# CONFIG_SDK is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_aria2=y/# CONFIG_PACKAGE_aria2 is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_ARIA2_BITTORRENT=y/# CONFIG_ARIA2_BITTORRENT is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_ARIA2_NOXML=y/# CONFIG_ARIA2_NOXML is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_ARIA2_OPENSSL=y/# CONFIG_ARIA2_OPENSSL is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_ARIA2_WEBSOCKET=y/# CONFIG_ARIA2_WEBSOCKET is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-aria2=y/# CONFIG_PACKAGE_luci-app-aria2 is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_ddns-scripts=y/# CONFIG_PACKAGE_ddns-scripts is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_ddns-scripts-services=y/# CONFIG_PACKAGE_ddns-scripts-services is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-ddns=y/# CONFIG_PACKAGE_luci-app-ddns is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_hd-idle=y/# CONFIG_PACKAGE_hd-idle is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-hd-idle=y/# CONFIG_PACKAGE_luci-app-hd-idle is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-nft-qos=y/# CONFIG_PACKAGE_luci-app-nft-qos is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_nft-qos=y/# CONFIG_PACKAGE_nft-qos is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_nlbwmon=y/# CONFIG_PACKAGE_nlbwmon is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-nlbwmon=y/# CONFIG_PACKAGE_luci-app-nlbwmon is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-watchcat=y/# CONFIG_PACKAGE_luci-app-watchcat is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_watchcat=y/# CONFIG_PACKAGE_watchcat is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_adblock=y/# CONFIG_PACKAGE_adblock is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-adblock=y/# CONFIG_PACKAGE_luci-app-adblock is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-minidlna=y/# CONFIG_PACKAGE_luci-app-minidlna is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_minidlna=y/# CONFIG_PACKAGE_minidlna is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_samba4-libs=y/# CONFIG_PACKAGE_samba4-libs is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_samba4-server=y/# CONFIG_PACKAGE_samba4-server is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_SAMBA4_SERVER_AVAHI=y/# CONFIG_SAMBA4_SERVER_AVAHI is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_SAMBA4_SERVER_NETBIOS=y/# CONFIG_SAMBA4_SERVER_NETBIOS is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_SAMBA4_SERVER_VFS=y/# CONFIG_SAMBA4_SERVER_VFS is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_SAMBA4_SERVER_WSDD2=y/# CONFIG_SAMBA4_SERVER_WSDD2 is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-samba4=y/# CONFIG_PACKAGE_luci-app-samba4 is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-smartdns=y/# CONFIG_PACKAGE_luci-app-smartdns is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_smartdns=y/# CONFIG_PACKAGE_smartdns is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_ttyd=y/# CONFIG_PACKAGE_ttyd is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-ttyd=y/# CONFIG_PACKAGE_luci-app-ttyd is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-upnp=y/# CONFIG_PACKAGE_luci-app-upnp is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_miniupnpd=y/# CONFIG_PACKAGE_miniupnpd is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_miniupnpd-nftables=y/# CONFIG_PACKAGE_miniupnpd-nftables is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_sqm-scripts=y/# CONFIG_PACKAGE_sqm-scripts is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-sqm=y/# CONFIG_PACKAGE_luci-app-sqm is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_luci-app-statistics=y/# CONFIG_PACKAGE_luci-app-statistics is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd=y/# CONFIG_PACKAGE_collectd is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-cpu=y/# CONFIG_PACKAGE_collectd-mod-cpu is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-cpufreq=y/# CONFIG_PACKAGE_collectd-mod-cpufreq is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-df=y/# CONFIG_PACKAGE_collectd-mod-df is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-interface=y/# CONFIG_PACKAGE_collectd-mod-interface is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-iwinfo=y/# CONFIG_PACKAGE_collectd-mod-iwinfo is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-load=y/# CONFIG_PACKAGE_collectd-mod-load is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-memory=y/# CONFIG_PACKAGE_collectd-mod-memory is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-network=y/# CONFIG_PACKAGE_collectd-mod-network is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-rrdtool=y/# CONFIG_PACKAGE_collectd-mod-rrdtool is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-thermal=y/# CONFIG_PACKAGE_collectd-mod-thermal is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-uptime=y/# CONFIG_PACKAGE_collectd-mod-uptime is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_collectd-mod-wireless=y/# CONFIG_PACKAGE_collectd-mod-wireless is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_vsftpd=y/# CONFIG_PACKAGE_vsftpd is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_wsdd2=y/# CONFIG_PACKAGE_wsdd2 is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_PACKAGE_wpad-mini=y/# CONFIG_PACKAGE_wpad-mini is not set/g' configs/rockchip/01-nanopi
sed -i -e 's/CONFIG_LUCI_LANG_bg=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ca=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_cs=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_de=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_el=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_es=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_fr=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_he=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_hi=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_hu=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_it=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ja=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ko=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_mr=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ms=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_pl=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_pt=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_pt_BR=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ro=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_ru=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_sk=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_sv=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_tr=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_uk=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_vi=y/# /g' configs/rockchip/02-luci_lang
sed -i -e 's/CONFIG_LUCI_LANG_zh_Hant=y/# /g' configs/rockchip/02-luci_lang
